title: Configuration
icon: 'mdi:cog'
id: configuration
path: configuration
badges: []
type: 'custom:grid-layout'
layout:
  #default
  grid-gap: var(--custom-layout-card-padding)
  grid-template-columns: 0 repeat(3, 1fr) 0
  grid-template-rows: 6vh repeat(1, fit-content(100%)) 0fr

  grid-template-areas: |
    "header  header         header       header     header"
    ".       low_batteries  .            .          ."
    ".       .            .            .          ."

  mediaquery:
    #phone
    "(max-width: 800px)":
      grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
      grid-template-columns: 0 repeat(1, 1fr) 0
      grid-template-rows: 8vh repeat(7, fit-content(100%)) 0fr
      grid-template-areas: |
        "header  header         header"      
        ".       low_batteries  ."
        ".       .              ."

    #tablet portrait
    "(max-width: 1000px)":
      grid-gap: calc(var(--custom-layout-card-padding))
      grid-template-columns: 0 repeat(2, 1fr) 0
      grid-template-rows: 6vh repeat(4, fit-content(100%)) 0fr
      grid-template-areas: |
        "header  header         header       header"
        ".       low_batteries  .            ."
        ".       .              .            ."
cards:
  #################################################
  #                    Header                     #
  #################################################

  - type: markdown
    view_layout:
      grid-area: header
    content: |
      # Other stuff

  #################################################
  #                  Low batteries                #
  #################################################
  - type: grid
    title: Low batteries
    view_layout:
      grid-area: low_batteries
    columns: 1
    square: false
    cards:
      - type: 'custom:auto-entities'
        card:
          show_header_toggle: false
          type: entities
        show_empty: true
        unique: true
        filter:
          exclude:
            - attributes:
                battery_report: false
          include:
            - entity_id: '/.*_battery(_level)?$/'
              options:
                icon: 'mdi:battery-alert'
                secondary_info: last-changed
              state: <= 30
