title: Configuration
icon: 'mdi:cog'
id: configuration
path: configuration
badges: []
type: 'custom:grid-layout'
layout:
  #default
  grid-column-gap: var(--custom-layout-card-padding)
  grid-template-columns: 0 repeat(3, 1fr) 0
  grid-template-rows: auto

  grid-template-areas: |
    ".       low_batteries  .            .          ."

  mediaquery:
    #phone
    "(max-width: 800px)":
      grid-template-columns: 0 repeat(1, 1fr) 0
      grid-template-areas: |
        ".       low_batteries  ."
        ".       .              ."

    #tablet portrait
    "(max-width: 1000px)":
      grid-template-columns: 0 repeat(2, 1fr) 0
      grid-template-areas: |
        ".       low_batteries  .            ."
cards:
  #################################################
  #                  Low batteries                #
  #################################################
  - type: custom:auto-entities
    view_layout:
      grid-area: low_batteries
    show_empty: true
    unique: true
    card:
      type: vertical-stack
      title: Low batteries
    card_param: cards
    filter:
      exclude:
        - attributes:
            battery_report: false
      include:
        - entity_id: '/.*_battery(_level)?$/'
          state: <= 30
          options:
            type: custom:mushroom-template-card
            entity_id: this.entity_id
            primary: |
              {{ state_attr('this.entity_id', 'friendly_name') }}
            secondary: |
              {{ states('this.entity_id') }} %
            icon: |
              {% if state_attr('this.entity_id', 'icon') %}
                {{ state_attr('this.entity_id', 'icon') }}
              {% else %}
                {% set percentage = states('this.entity_id') | round(-1) | round %}
                mdi:battery-{{percentage}}
              {% endif %}
            icon_color: |
              {% if (states('this.entity_id') | int) <= 15 %}
                red
              {% else %}
                orange
              {% endif %}
