---
id: upstairs_bedroom_detect_person_in_bed
alias: Upstairs Bedroom - Detect person in bed
trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_bedroom_shock_sensor_left_motion
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.upstairs_bedroom_shock_sensor_right_motion
    from: "off"
    to: "on"
variables:
  target_boolean: |
    {% if trigger.entity_id == 'binary_sensor.upstairs_bedroom_shock_sensor_left_motion' -%}
      input_boolean.upstairs_bedroom_mf_in_bed
    {%- else -%}
      input_boolean.upstairs_bedroom_bs_in_bed
    {%- endif %}
condition:
  and:
    - condition: time
      after: "21:00:00"
      before: "06:00:00"
    - condition: template
      value_template: |
        {{ is_state(target_boolean, 'off') }}
action:
  - service: input_boolean.turn_on
    data:
      entity_id: "{{ target_boolean }}"
