---
id: upstairs_bedroom_nightstand_manyie_automatic_on
alias: Upstairs Bedroom - Nightstand ManYie automatic on
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: "on"

condition:
  - condition: state
    entity_id: input_boolean.upstairs_bedroom_mf_in_bed
    state: "off"

action:
  - service: scene.turn_on
    data:
      entity_id: scene.upstairs_bedroom_lights_nightstand_manyie_dimmed
      transition: 2
