---
id: home_alarm_pending
alias: Home - Alarm pending
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'

action:
  - alias: "Alert beep on tablets"
    event: wallpanels_publish_payload
    event_data:
      payload: |
        {
          "audio": "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-alarm.mp3"
        }

  - alias: "Show alarm popup on tablets"
    service: browser_mod.popup
    data:
      deviceID:
        - tablet-hallway
        - tablet-garage
      title: Alarm
      large: false
      card:
        type: 'custom:alarmo-card'
        entity: alarm_control_panel.house
        keep_keypad_visible: true

  - alias: "Wake up tablets"
    event: wallpanels_publish_payload
    event_data:
      payload: |
        {
          "wake": true
        }
