---
id: home_alarm_arm_away_automatically
alias: Home - Alarm - Arm Away automatically
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    to: "on"

condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: "disarmed"

action:
  - alias: Arm alarm
    service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.house
