---
id: home_alarm_disarmed
alias: Home - Alarm disarmed
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'

action:
  - alias: "Close alarm popup on tablets"
    service: browser_mod.close_popup
    data:
      deviceID:
        - tablet-hallway
        - tablet-garage

  - service: switch.turn_off
    data:
      entity_id: switch.upstairs_hallway_siren

  # OK beep
  - choose:
    # Only beep if bedtime mode is off
    - conditions:
        - condition: state
          entity_id: input_boolean.home_modes_bedtime_mode
          state:  'off'
      sequence:
        - event: wallpanels_publish_payload
          event_data:
            payload: |
              {
                "audio": "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-ok.mp3"
              }
