---
id: home_alarm_pending
alias: Home - Alarm pending
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: "pending"

action:
  - alias: "Alert beep on tablets"
    service: media_player.play_media
    target:
      device_id:
        - 11355f46d7934d151cb35527a01b7e74 # Tablet Hallway
        - 7be8a11efbbb6f8bb932185edcd533a6 # Tablet Garage
    data:
      media_content_id: "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-alarm.mp3"
      media_content_type: music

  - alias: "Wake up tablets"
    service: switch.turn_off
    entity_id:
      - switch.garage_tablet_screensaver
      - switch.downstairs_hallway_tablet_screensaver

  - alias: "Show alarm popup on tablets"
    service: browser_mod.popup
    data:
      browser_id:
        - tablet-garage-fullykiosk
        - tablet-hallway-fullykiosk
      dismissable: false
      size: normal
      content:
        type: "custom:alarmo-card"
        entity: alarm_control_panel.house
        name: "Alarm"
        keep_keypad_visible: false
        button_scale_actions: 1.3
        button_scale_keypad: 1.3
        card_mod:
          style: |-
            ha-card {
              box-shadow: none;
            }
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog div.mdc-dialog__scrim {
              background: rgba(0, 100, 100, 0.4);
            }
            div.mdc-dialog__container {
              --vertical-align-dialog: center !important;
            }
          .: |
            ha-dialog {
              --dialog-backdrop-filter: blur(0.8em);
            }
