---
id: home_alarm_arming
alias: Home - Alarm arming
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'arming'

action:
  # Warning beep wall panels
  - event: wallpanels_publish_payload
    event_data:
      payload: |
        {
          "audio": "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-warning.mp3"
        }
