---
id: home_alarm_pending
alias: Home - Alarm pending
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'

action:
  - alias: "Alert beep on tablets"
    service: media_player.play_media
    entity_id:
      - media_player.downstairs_garage_tablet
      - media_player.downstairs_hallway_tablet
    data:
      media_content_id: "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-alarm.mp3"
      media_content_type: music

  - alias: "Wake up tablets"
    service: switch.turn_off
    entity_id:
      - switch.downstairs_hallway_tablet_screensaver
      - switch.downstairs_garage_tablet_screensaver

  - alias: "Show alarm popup on tablets"
    service: browser_mod.popup
    data:
      browser_id:
        - hallway-fullykiosk
        - garage-fullykiosk
      title: Alarm
      content:
        type: custom:alarmo-card
        entity: alarm_control_panel.house
        keep_keypad_visible: true
      size: wide
      dismissable: false
