---
id: home_alarm_pending
alias: Home - Alarm pending
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'

action:
  - alias: "Alert beep on tablets"
    service: fullykiosk.play_audio
    entity_id:
      - media_player.downstairs_hallway_tablet_media_player
      - media_player.downstairs_garage_tablet_media_player
    data:
      url: "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-alarm.mp3"
      stream: 1

  - alias: "Wake up tablets"
    service: switch.turn_off
    entity_id:
      - switch.downstairs_hallway_tablet_screensaver
      - switch.downstairs_garage_tablet_screensaver

  - alias: "Show alarm popup on tablets"
    service: browser_mod.popup
    data:
      deviceID:
        - tablet-hallway
        - tablet-garage
      title: Alarm
      large: false
      card:
        type: 'custom:alarmo-card'
        entity: alarm_control_panel.house
        keep_keypad_visible: true
