---
id: home_alarm_triggered
alias: Home - Alarm triggered
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'

action:
  # Sound the alarm
  - service: siren.turn_on
    data:
      entity_id: siren.upstairs_hallway_siren
