---
id: home_bedtime_mode_off
alias: Home - Bedtime mode off
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: 'off'

action:
  # Undim tablet audio
  - event: wallpanels_publish_payload
    event_data:
      payload: |
        {
          "volume": 80
        }
