---
id: home_bedtime_mode_on_turn_off_lights
alias: Home - Bedtime mode on turn off lights
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: 'on'

action:
  - service: scene.turn_on
    data:
      entity_id: scene.backyard_lights_off

  - service: input_select.select_option
    data:
      entity_id: input_select.kitchen_lights_scene
      option: 'Off'

  - service: input_select.select_option
    data:
      entity_id: input_select.downstairs_living_room_lights_scene
      option: 'Off'

  - service: input_select.select_option
    data:
      entity_id: input_select.downstairs_dining_area_lights_scene
      option: 'Off'

  - service: input_select.select_option
    data:
      entity_id: input_select.attic_office_lights_scene
      option: 'Off'

  - service: scene.turn_on
    data:
      entity_id: scene.attic_hallway_lights_off

  - service: light.turn_off
    entity_id: light.bedroom_ceiling
