---
id: home_guest_mode_automatic_off
alias: Home - Guest mode automatic off
trigger:
  - platform: state
    entity_id: person.bernd
    to: 'home'
  - platform: state
    entity_id: person.man_yie
    to: 'home'

action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.home_modes_guest_mode
