---
id: notifications_doorbell_triggered
alias: Notifications - Doorbell triggered

mode: single
max_exceeded: silent

trigger:
  platform: state
  entity_id: binary_sensor.doorbell_visitor
  to: "on"

variables:
  # The external url for the Home Assistant instance
  base_url: "{{ states('sensor.system_url_external') }}"
  # Person count
  person_count: "{{ states('sensor.doorbell_person_count') }}"
  # Camera entity
  camera: camera.doorbell
  # Notification target
  notify_device: adults
  # Rate limit the automation to once per 30 seconds
  cooldown: 30

condition:
  # - condition: template
  #   value_template: "{{ person_count > 0 }}"

action:
  - service: camera.snapshot
    data:
      entity_id: "{{ camera }}"
      filename: /config/www/images/snapshots/driveway.jpg

  - delay: "00:00:01"

  - service: "notify.{{ notify_device }}"
    data:
      title: "Doorbell"
      message: "There is somebody at the door"
      data:
        image: >-
          {{ base_url }}/local/images/snapshots/driveway.jpg

  - delay:
      seconds: "{{ cooldown }}"
