---
id: notification_alarm_invalid_code
alias: Notifications - Alarm invalid code
trigger:
  - platform: event
    event_type: alarmo_failed_to_arm
    event_data:
      reason: invalid_code

variables:
  # Notification target
  notify_devices:
    - mobile_app_iphone_bernd
    - mobile_app_iphone_man_yie

action:
  - alias: Send a notification to each device
    repeat:
        for_each: "{{ notify_devices }}"
        sequence:
          - service: "notify.{{ repeat.item }}"
            data:
              message: Invalid code entered for alarm
              data:
                group: 'alarm'
                sound: none
