---
id: bedroom_ceiling_light_on
alias: Bedroom - Ceiling light on
trigger:
  - id: bedroom_switch_top
    platform: device
    domain: hue
    device_id: 5dd7987abfcc60204c7752b0ad06fdd6
    type: initial_press
    subtype: 3
    unique_id: 57387348-dc48-484d-b6df-882e68adee7c
action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_lights_ceiling_on
