---
id: bedroom_ceiling_light_off
alias: Bedroom - Ceiling light off
trigger:
  - platform: device
    domain: mqtt
    device_id: 1eb8a1cbd7e1baf762316b075b3be5c0
    type: action
    subtype: press_2_and_4
    discovery_id: 0x00000000017579b6 action_press_2_and_4
  - platform: device
    domain: mqtt
    device_id: 1eb8a1cbd7e1baf762316b075b3be5c0
    type: action
    subtype: press_2
    discovery_id: 0x00000000017579b6 action_press_2
  - platform: device
    domain: mqtt
    device_id: 1eb8a1cbd7e1baf762316b075b3be5c0
    type: action
    subtype: press_4
    discovery_id: 0x00000000017579b6 action_press_4
action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_lights_ceiling_off
