---
id: bedroom_nightstand_bernd_toggle
alias: Bedroom - Nightstand Bernd toggle
trigger:
  - platform: device
    domain: mqtt
    device_id: 16ddfbe0fa5d3d2f9839f22c06427b62
    type: action
    subtype: arrow_right_click
    discovery_id: 0x90fd9ffffe9096ea action_arrow_right_click
  - platform: device
    domain: mqtt
    device_id: 3c3de2878a774facced71f8d1df4fa75
    type: action
    subtype: toggle
    discovery_id: 0x90fd9ffffed252a4 action_toggle
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_bernd
        state: 'off'
      sequence:
        - scene: scene.bedroom_lights_nightstand_bernd_dimmed
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_bernd
        state: 'on'
      sequence:
        - scene: scene.bedroom_lights_nightstand_bernd_off

    # Default
    default: []
