---
id: bedroom_nightstand_manyie_automatic_on
alias: Bedroom - Nightstand ManYie automatic on
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: "on"

condition:
  - condition: state
    entity_id: binary_sensor.bedroom_bed_occupancy_left
    state: "off"

action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_lights_nightstand_manyie_dimmed
      transition: 2
