---
id: living_room_lights_off
alias: Living Room - Lights off
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.living_room_switch
    to: recall_scene_2
action:
  - scene: scene.living_room_lights_off
