---
id: living_room_lights_on
alias: Living Room - Lights on
trigger:
  - platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: recall_scene_0
    discovery_id: 0x0000000001715691 action_recall_scene_0
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_lights_full_brightness
