---
id: living_room_lights_off
alias: Living Room - Lights off
trigger:
  - platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_2
    discovery_id: 0x0000000001715691 action_press_2
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_lights_off
