---
id: living_room_lights_on
alias: Living Room - Lights on
trigger:
  - platform: state
    entity_id: sensor.living_room_switch
    to: recall_scene_3
action:
  - scene: scene.living_room_lights_full_brightness
