---
id: living_room_lights_on
alias: Living Room - Lights on
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_switch_top
    to: 'on'
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_lights_full_brightness
