---
id: living_room_vacuum_error
alias: Living Room - Vacuum Error
max_exceeded: silent
trigger:
  - platform: state
    entity_id: vacuum.living_area_vacuum
    to: "error"
action:
  - service: notify.slack_bot
    data:
      message: |
        🔴 MiMi error: {{ state_attr('vacuum.living_area_vacuum', 'valetudo_state').name }}
