---
id: downstairs_living_room_harmony_activity_stops_sonos
alias: Downstairs living room - Harmony activity stops sonos
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.downstairs_living_room_current_harmony_activity
condition:
  not:
    - condition: state
      entity_id: sensor.downstairs_living_room_current_harmony_activity
      state: Listen to Sonos
    - condition: state
      entity_id: sensor.downstairs_living_room_current_harmony_activity
      state: PowerOff
action:
  - service: media_player.media_stop
    data:
      entity_id:
        - media_player.kitchen_sonos
        - media_player.living_room_sonos
