---
id: downstairs_living_room_lights_scene_controller
alias: Downstairs living room - Lights - Scene controller
mode: restart

trigger:
  - id: living_room_switch_top
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_1
    discovery_id: 0x0000000001715691 action_press_1

  - id: living_room_switch_top
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_3
    discovery_id: 0x0000000001715691 action_press_3

  - id: living_room_switch_top
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_1_and_3
    discovery_id: 0x0000000001715691 action_press_1_and_3

  - id: living_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_2
    discovery_id: 0x0000000001715691 action_press_2

  - id: living_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_4
    discovery_id: 0x0000000001715691 action_press_4

  - id: living_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 030ecf5d6e97435dfceeffb7c5e0d5b0
    type: action
    subtype: press_2_and_4
    discovery_id: 0x0000000001715691 action_press_2_and_4

  - id: downstairs_living_room_is_dark
    platform: state
    entity_id: binary_sensor.living_room_is_dark
    to: "on"

  - id: downstairs_living_room_motion_detected
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_occupancy
    to: "on"

  - id: downstairs_living_room_media_playing
    platform: state
    entity_id: binary_sensor.downstairs_living_room_media_playing

  - id: downstairs_living_room_no_longer_dark
    platform: state
    entity_id: binary_sensor.living_room_is_dark
    to: "off"
    for: "00:02:00"

  - id: downstairs_no_presence_for_60_min
    platform: state
    entity_id: binary_sensor.downstairs_presence
    to: "off"
    for: "01:00:00"

  - id: lights_turned_off
    platform: state
    entity_id: light.downstairs_living_room
    from: "on"
    to: "off"

variables:
  scene_helper: input_select.downstairs_living_room_lights_scene

action:
  - alias: "choose scene based on trigger"
    choose:
      # Loop through scenes with button
      - conditions:
        - or:
          - condition: trigger
            id: living_room_switch_top
        sequence:
          - service: script.input_select_next_with_skip
            data:
              entity_id: "{{ scene_helper }}"
              skip_options:
                - "Off"
                - "Movie mode"

      # Turn on automatically to a specific scene
      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.downstairs_living_room_automatic_lights
                state: "on"
              - condition: state
                entity_id: binary_sensor.living_room_is_dark
                state: "on"
              - or:
                  - and:
                      - condition: trigger
                        id: downstairs_living_room_is_dark
                      - condition: state
                        entity_id: binary_sensor.downstairs_presence
                        state: "on"
                  - condition: trigger
                    id: downstairs_living_room_media_playing
                  - condition: trigger
                    id: downstairs_living_room_motion_detected
        sequence:
          - choose:
              # Only set these scenes in the evening
              - conditions:
                  - or:
                      - alias: "Late evening"
                        condition: state
                        entity_id: sensor.system_time_of_day_detailed
                        state: "late_evening"
                      - alias: "night"
                        condition: state
                        entity_id: sensor.system_time_of_day_detailed
                        state: "night"
                sequence:
                  - choose:
                      # Select "Movie mode"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "on"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Movie mode"

                      # Select "Relaxed"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "off"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Relaxed"

            # Select "Full brightness"
            default:
              - service: input_select.select_option
                data:
                  entity_id: "{{ scene_helper }}"
                  option: "Full brightness"

      # Select "off" scene
      - conditions:
          - or:
              # Turned off manually
              - condition: trigger
                id: living_room_switch_bottom_left
              - condition: trigger
                id: living_room_switch_bottom_right
              - condition: trigger
                id: living_room_switch_bottom
              - condition: trigger
                id: lights_turned_off
              # Turn off automatically
              - and:
                  - condition: state
                    entity_id: binary_sensor.downstairs_living_room_automatic_lights
                    state: "on"
                  - or:
                      - condition: trigger
                        id: downstairs_no_presence_for_60_min
                      - condition: trigger
                        id: downstairs_living_room_no_longer_dark
        sequence:
          - service: input_select.select_option
            data:
              entity_id: "{{ scene_helper }}"
              option: "Off"
