---
id: downstairs_living_room_lights_scene_controller
alias: Downstairs living room - Lights - Scene controller
mode: restart

trigger:
  - id: downstairs_living_room_switch_top
    platform: device
    domain: hue
    device_id: 3edece83f587e6ea9a3943faf8ba29f8
    type: initial_press
    subtype: 3
    unique_id: fe1b1157-c89c-47d7-83f5-b457252948fb

  - id: downstairs_living_room_switch_bottom
    platform: device
    domain: hue
    device_id: 3edece83f587e6ea9a3943faf8ba29f8
    type: initial_press
    subtype: 4
    unique_id: 32367223-1912-4de9-8a2c-8e9063ce66f9

  - id: downstairs_living_room_is_dark
    platform: state
    entity_id: binary_sensor.downstairs_living_room_is_dark
    to: "on"

  - id: downstairs_living_room_motion_detected
    platform: state
    entity_id: binary_sensor.downstairs_living_room_motion
    to: "on"

  - id: downstairs_living_room_media_playing
    platform: state
    entity_id: binary_sensor.downstairs_living_room_media_playing

  - id: downstairs_living_room_no_longer_dark
    platform: state
    entity_id: binary_sensor.downstairs_living_room_is_dark
    to: "off"
    for: "00:02:00"

  - id: downstairs_no_presence_for_60_min
    platform: state
    entity_id: binary_sensor.downstairs_presence
    to: "off"
    for: "01:00:00"

  - id: lights_turned_off
    platform: state
    entity_id: light.downstairs_living_room
    from: 'on'
    to: 'off'

variables:
  scene_helper: input_select.downstairs_living_room_lights_scene

action:
  - alias: "choose scene based on trigger"
    choose:
      # Loop through scenes with button
      - conditions:
          - condition: trigger
            id: downstairs_living_room_switch_top
        sequence:
          - service: script.input_select_next_with_skip
            data:
              entity_id: "{{ scene_helper }}"
              skip_options:
                - "Off"
                - "Movie mode"

      # Turn on automatically to a specific scene
      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.downstairs_living_room_automatic_lights
                state: "on"
              - condition: state
                entity_id: binary_sensor.downstairs_living_room_is_dark
                state: "on"
              - or:
                  - and:
                      - condition: trigger
                        id: downstairs_living_room_is_dark
                      - condition: state
                        entity_id: binary_sensor.downstairs_presence
                        state: "on"
                  - condition: trigger
                    id: downstairs_living_room_media_playing
                  - condition: trigger
                    id: downstairs_living_room_motion_detected
        sequence:
          - choose:
              # Only set these scenes in the evening
              - conditions:
                  - or:
                      - alias: "Late evening"
                        condition: state
                        entity_id: sensor.system_time_of_day_detailed
                        state: "late_evening"
                      - alias: "night"
                        condition: state
                        entity_id: sensor.system_time_of_day_detailed
                        state: "night"
                sequence:
                  - choose:
                      # Select "Movie mode"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "on"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Movie mode"

                      # Select "Relaxed"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "off"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Relaxed"

            # Select "Full brightness"
            default:
              - service: input_select.select_option
                data:
                  entity_id: "{{ scene_helper }}"
                  option: "Full brightness"

      # Select "off" scene
      - conditions:
          - or:
              # Turned off manually
              - condition: trigger
                id: downstairs_living_room_switch_bottom
              - condition: trigger
                id: lights_turned_off
              # Turn off automatically
              - and:
                  - condition: state
                    entity_id: binary_sensor.downstairs_living_room_automatic_lights
                    state: "on"
                  - or:
                      - condition: trigger
                        id: downstairs_no_presence_for_60_min
                      - condition: trigger
                        id: downstairs_living_room_no_longer_dark
        sequence:
          - service: input_select.select_option
            data:
              entity_id: "{{ scene_helper }}"
              option: "Off"
