---
id: downstairs_living_room_vacuum_runs_when_away
alias: Downstairs living room - Vacuum runs when away
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: "off"
    to: "on"
condition:
  and:
    - condition: state
      entity_id: input_boolean.downstairs_living_room_vacuum_ran_today
      state: "off"
    - condition: state
      entity_id: vacuum.valetudo_livingroom
      state: "docked"
    - condition: state
      entity_id: input_boolean.downstairs_vacuum_automatic_cleaning_active
      state: "on"
action:
  - service: script.turn_on
    data:
      entity_id: script.vacuum_downstairs
