---
id: kitchen_lights_scene_controller
alias: Kitchen - Lights - Scene controller
max_exceeded: silent

trigger:
  - id: kitchen_switch_top
    platform: device
    domain: mqtt
    device_id: cd02dc4dd7d89d84f13b6d1bc9a91efe
    type: action
    subtype: press_1
    discovery_id: 0x0000000001715668 action_press_1

  - id: kitchen_switch_bottom
    platform: device
    domain: mqtt
    device_id: cd02dc4dd7d89d84f13b6d1bc9a91efe
    type: action
    subtype: press_2
    discovery_id: 0x0000000001715668 action_press_2

  - id: kitchen_motion_detected
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    to: 'on'

  - id: automatic_lights_timer_finished
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_automatic_lights

variables:
  scene_helper: input_select.kitchen_lights_scene
  automatic_lights_duration: "{{ (states('input_number.automatic_lights_duration_kitchen') | float(0)) * 60 }}"

action:
  - alias: "choose scene based on trigger"
    choose:
      # Turn on with switch
      - conditions:
          - condition: trigger
            id: kitchen_switch_top
        sequence:
          - service: input_select.select_option
            data:
              entity_id: "{{ scene_helper }}"
              option: "Full brightness"

      # Turn on automatically
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.kitchen_automatic_lights
                state: "on"
              - condition: state
                entity_id: binary_sensor.kitchen_is_dark
                state: "on"
              - condition: or
                conditions:
                  - condition: trigger
                    id: kitchen_motion_detected

        sequence:
          - choose:
              # Only set these scenes in the evening
              - conditions:
                  - condition: time
                    after: "20:00:00"
                    before: "08:00:00"
                sequence:
                  - service: input_select.select_option
                    data:
                      entity_id: "{{ scene_helper }}"
                      option: "Relaxed"

            # Select "Full brightness"
            default:
              - service: input_select.select_option
                data:
                  entity_id: "{{ scene_helper }}"
                  option: "Full brightness"
          
          - service: timer.start
            data:
              entity_id: timer.kitchen_automatic_lights
              duration: "{{ automatic_lights_duration }}"

      # Select "off" scene
      - conditions:
          - condition: or
            conditions:
              # Turned off manually
              - condition: trigger
                id: kitchen_switch_bottom
              # Turn off automatically
              - condition: trigger
                id: automatic_lights_timer_finished

        sequence:
          - service: input_select.select_option
            data:
              entity_id: "{{ scene_helper }}"
              option: "Off"
