---
id: kitchen_morning_start_coffee_machine
alias: Kitchen - Morning - Start coffee machine
max_exceeded: silent
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: "off"

condition:
  - alias: "Early morning"
    condition: state
    entity_id: sensor.system_time_of_day_detailed
    state: "early_morning"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.kitchen_automatic_coffee_schedule
            state: "Weekend"
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: "off"
        sequence:
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_coffee_maker_power

      - conditions:
          - condition: state
            entity_id: input_select.kitchen_automatic_coffee_schedule
            state: "Always"
        sequence:
          - service: switch.turn_on
            data:
              entity_id: switch.kitchen_coffee_maker_power
