---
id: kitchen_morning_start_sonos
alias: Kitchen - Morning - Start Sonos
max_exceeded: silent
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: "off"

condition:
  - alias: "Early morning"
    condition: state
    entity_id: sensor.system_time_of_day_detailed
    state: "early_morning"

  - not:
      - condition: state
        entity_id: media_player.kitchen_sonos
        state: "playing"

action:
  - service: media_player.join
    target:
      device_id: 2826348595450dea784b9ad8cfc88135
    data:
      group_members:
        - media_player.living_room_sonos
        - media_player.living_room_sonos_move
  - service: media_player.volume_set
    data:
      entity_id:
        - media_player.living_room_sonos
        - media_player.living_room_sonos_move
        - media_player.kitchen_sonos
      volume_level: 0.04
  - service: media_player.select_source
    target:
      device_id: 2826348595450dea784b9ad8cfc88135
    data:
      source: Qmusic
