---
id: driveway_automatic_lights_off
alias: Driveway - Automatic lights off
trigger:
  - platform: state
    entity_id: light.driveway_wall
    to: "on"
    for:
      minutes: 10
condition:
  and:
    - condition: state
      entity_id: binary_sensor.driveway_automatic_lights
      state: 'on'
action:
  - scene: scene.driveway_lights_off
