---
id: driveway_automatic_lights_timer_start
alias: Driveway - Automatic lights timer start
trigger:
  - platform: state
    entity_id: light.driveway_wall
    to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.driveway_automatic_lights
    state: "on"
action:
  - service: timer.start
    data:
      entity_id: timer.driveway_automatic_lights
      duration: "{{ (states('input_number.driveway_automatic_lights_duration') | float(0)) * 60 }}"
