---
id: driveway_automatic_lights_on
alias: Driveway - Automatic lights on
trigger:
  - platform: state
    entity_id: binary_sensor.driveway_motion
    from: "off"
    to: "on"
condition:
  and:
    - condition: state
      entity_id: binary_sensor.driveway_automatic_lights
      state: "on"
    - condition: state
      entity_id: light.driveway_wall
      state: "off"
    - or:
        - condition: state
          entity_id: binary_sensor.driveway_is_dusk
          state: "on"
        - condition: state
          entity_id: binary_sensor.driveway_is_dark
          state: "on"
action:
  - service: automation.trigger
    data:
      entity_id: automation.driveway_lights_on
