---
id: downstairs_dining_area_automatic_lights_on_morning
alias: Downstairs dining area - Automatic lights on morning
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door_contact
    to: "on"
condition:
  and:
    - alias: "Automatic lights should be enabled"
      condition: state
      entity_id: binary_sensor.downstairs_dining_area_automatic_lights
      state: "on"
    - alias: "Area should be dark"
      condition: state
      entity_id: binary_sensor.downstairs_dining_area_is_dark
      state: "on"
    - alias: "Lights should be off"
      condition: state
      entity_id: light.dining_area
      state: "off"
    - alias: "Early morning"
      condition: state
      entity_id: sensor.system_time_of_day_detailed
      state: "early_morning"
    - alias: "Recent motion detected in hallway"
      condition: template
      value_template: |
        {% set entity = "binary_sensor.downstairs_hallway_motion" %}
        {% if states[entity] %}
          {% set last_changed = as_timestamp(states[entity].last_changed) %}
        {% else %}
          {% set last_changed = 0 %}
        {% endif %}
        {{
          (as_timestamp(now()) - last_changed) < 180
        }}
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.downstairs_dining_area_lights_scene
      option: "Relaxed"
