---
id: downstairs_dining_area_lights_scene_controller
alias: Downstairs dining area - Lights - Scene controller
max_exceeded: silent

trigger:
  - id: downstairs_dining_area_switch_top
    platform: device
    domain: hue
    device_id: e2c68b8b1646561244951cc00dc50d84
    type: initial_press
    subtype: 3
    unique_id: ca5a3154-403a-46ab-aedb-4218a1960505

  - id: downstairs_dining_area_switch_bottom
    platform: device
    domain: hue
    device_id: e2c68b8b1646561244951cc00dc50d84
    type: initial_press
    subtype: 4
    unique_id: 2f953c8e-57d8-449b-9d9b-6bd8d040c947

  - id: downstairs_dining_area_is_dark
    platform: state
    entity_id: binary_sensor.downstairs_dining_area_is_dark
    to: "on"

  - id: downstairs_dining_area_motion_detected
    platform: state
    entity_id: binary_sensor.downstairs_dining_area_motion
    to: "on"

  - id: downstairs_living_room_media_playing
    platform: state
    entity_id: binary_sensor.downstairs_living_room_media_playing

  - id: downstairs_dining_area_no_longer_dark
    platform: state
    entity_id: binary_sensor.downstairs_dining_area_is_dark
    to: "off"
    for: "00:02:00"

  - id: downstairs_no_presence_for_60_min
    platform: state
    entity_id: binary_sensor.downstairs_presence
    to: "off"
    for: "01:00:00"

  - id: lights_turned_off
    platform: state
    entity_id: light.downstairs_dining_area
    from: 'on'
    to: 'off'

variables:
  scene_helper: input_select.downstairs_dining_area_lights_scene

action:
  - alias: "choose scene based on trigger"
    choose:
      # Loop through scenes with button
      - conditions:
          - condition: trigger
            id: downstairs_dining_area_switch_top
        sequence:
          - service: script.input_select_next_with_skip
            data:
              entity_id: "{{ scene_helper }}"
              skip_options:
                - "Off"
                - "Movie mode"

      # Turn on automatically to a specific scene
      - conditions:
          - and:
              - condition: state
                entity_id: binary_sensor.downstairs_dining_area_automatic_lights
                state: "on"
              - condition: state
                entity_id: binary_sensor.downstairs_dining_area_is_dark
                state: "on"
              - or:
                  - and:
                      - condition: trigger
                        id: downstairs_dining_area_is_dark
                      - condition: state
                        entity_id: binary_sensor.downstairs_presence
                        state: "on"
                  - condition: trigger
                    id: downstairs_living_room_media_playing
                  - condition: trigger
                    id: downstairs_dining_area_motion_detected
        sequence:
          - choose:
              # Only set these scenes in the evening
              - conditions:
                  - or:
                      - alias: "Late evening"
                        condition: state
                        entity_id: sensor.system_time_of_day
                        state: "late_evening"
                      - alias: "night"
                        condition: state
                        entity_id: sensor.system_time_of_day
                        state: "night"
                sequence:
                  - choose:
                      # Select "Movie mode"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "on"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Movie mode"

                      # Select "Relaxed"
                      - conditions:
                          - condition: state
                            entity_id: binary_sensor.downstairs_living_room_media_playing
                            state: "off"
                        sequence:
                          - service: input_select.select_option
                            data:
                              entity_id: "{{ scene_helper }}"
                              option: "Relaxed"

            # Select "Full brightness"
            default:
              - service: input_select.select_option
                data:
                  entity_id: "{{ scene_helper }}"
                  option: "Full brightness"

      # Select "off" scene
      - conditions:
          - or:
              # Turned off manually
              - condition: trigger
                id: downstairs_dining_area_switch_bottom
              - condition: trigger
                id: lights_turned_off
              # Turn off automatically
              - and:
                  - condition: state
                    entity_id: binary_sensor.downstairs_dining_area_automatic_lights
                    state: "on"
                  - or:
                      - condition: trigger
                        id: downstairs_no_presence_for_60_min
                      - condition: trigger
                        id: downstairs_dining_area_no_longer_dark
        sequence:
          - service: input_select.select_option
            data:
              entity_id: "{{ scene_helper }}"
              option: "Off"
