---
id: hallway_attic_ceiling_light_on
alias: Hallway Attic - Ceiling light on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: 4b41fc02c4f375ddbe1c405fe173600d
    type: action
    subtype: recall_scene_0
    discovery_id: 0x0000000001716b46 action_recall_scene_0
action:
  - scene: scene.hallway_attic_lights_on
