---
id: kitchen_automatic_lights_on
alias: Kitchen - Automatic lights on
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.automatic_lights_kitchen
      state: 'on'
    - condition: state
      entity_id: binary_sensor.is_dark_kitchen
      state: 'on'
action:
  - choose:
    - conditions:
        - condition: time
          after: "19:30:00:00"
          before: "02:00:00"
      sequence:
        - scene: scene.kitchen_lights_relaxed
    
    default:
      - scene: scene.kitchen_lights_full_brightness

  - service: timer.start
    data:
      entity_id: timer.automatic_lights_kitchen
      duration: "{{ (states('input_number.automatic_lights_duration_kitchen') | float) * 60 }}"
