---
id: kitchen_automatic_lights_off
alias: Kitchen - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.automatic_lights_kitchen
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.automatic_lights_kitchen
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'on'
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_motion
          state:  'on'
      sequence:
        - service: timer.start
          data:
            entity_id: timer.automatic_lights_kitchen
            duration: "{{ (states('input_number.automatic_lights_duration_kitchen') | float) * 60 }}"

    default:
      - service: scene.turn_on
        data:
          entity_id: scene.kitchen_lights_off
          transition: 2
