---
id: kitchen_lights_on
alias: Kitchen - Lights on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.kitchen_switch
    to: recall_scene_0
action:
  - scene: scene.kitchen_lights_full_brightness
