---
id: upstairs_bedroom_eva_ceiling_light_on
alias: Upstairs Bedroom Eva - Ceiling light on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: 8cf6a875598638035406a6c34f99ffc6
    type: action
    subtype: press_1_and_3
    discovery_id: 0x00000000017579ae action_press_1_and_3
  - platform: device
    domain: mqtt
    device_id: 8cf6a875598638035406a6c34f99ffc6
    type: action
    subtype: press_1
    discovery_id: 0x00000000017579ae action_press_1
  - platform: device
    domain: mqtt
    device_id: 8cf6a875598638035406a6c34f99ffc6
    type: action
    subtype: press_3
    discovery_id: 0x00000000017579ae action_press_3
action:
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "08:30:00"
        sequence:
          - service: scene.turn_on
            data:
              entity_id: scene.upstairs_bedroom_eva_lights_ceiling_on
              transition: 120

    # - conditions:
    #     - condition: state
    #       entity_id: light.upstairs_bedroom_eva_ceiling
    #       state: 'on'
    #   sequence:
    #     - scene: scene.upstairs_bedroom_eva_lights_ceiling_off

    # Default
    default:
      - service: scene.turn_on
        data:
          entity_id: scene.upstairs_bedroom_eva_lights_ceiling_on
