---
id: upstairs_bedroom_eva_nightlight_automatic_off
alias: Upstairs Bedroom Eva - Nightlight Automatic off
max_exceeded: silent
trigger:
  - platform: state
    entity_id: light.upstairs_bedroom_eva_ceiling
    from: "off"
    to: "on"
condition:
  - condition: state
    entity_id: light.upstairs_bedroom_eva_nightlight
    state: "on"
action:
  - service: scene.turn_on
    data:
      entity_id: scene.upstairs_bedroom_eva_lights_nightlight_off
