---
id: backyard_automatic_lights_on
alias: Backyard - Automatic lights on
trigger:
  - platform: state
    entity_id: binary_sensor.driveway_is_dusk
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.backyard_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.backyard
      state: 'off'
action:
  - service: automation.trigger
    data:
      entity_id: automation.backyard_lights_on
