---
id: backyard_automatic_lights_off
alias: Backyard - Automatic lights off
trigger:
  - platform: time
    at: "23:00"
  - platform: state
    entity_id: binary_sensor.driveway_is_dusk
    to: 'off'
condition:
  and:
    - condition: state
      entity_id: binary_sensor.backyard_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.backyard
      state: 'on'
action:
  - service: automation.trigger
    data:
      entity_id: automation.backyard_lights_off
