---
id: backyard_lights_off
alias: Backyard - Lights off
max_exceeded: silent
trigger:
  - id: utility_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 64f3bc4a9faf96bc47150c1c680d3fa5
    type: action
    subtype: press_2
    discovery_id: 0x00000000017611ab action_press_2

  - id: utility_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 64f3bc4a9faf96bc47150c1c680d3fa5
    type: action
    subtype: press_4
    discovery_id: 0x00000000017611ab action_press_4

  - id: utility_room_switch_bottom
    platform: device
    domain: mqtt
    device_id: 64f3bc4a9faf96bc47150c1c680d3fa5
    type: action
    subtype: press_2_and_4
    discovery_id: 0x00000000017611ab action_press_2_and_4
action:
  - scene: scene.backyard_lights_off
