---
id: backyard_lights_on
alias: Backyard - Lights on
max_exceeded: silent
trigger:
  - id: utility_room_switch_top
    platform: device
    domain: hue
    device_id: 17b4abf9c9be5049601d8c59995a94c1
    type: initial_press
    subtype: 3
    unique_id: 916b37bf-4936-4acd-a901-82bad7be82ab
action:
  - scene: scene.backyard_lights_on
