---
id: hallway_downstairs_lights_scene_changed
alias: Hallway Downstairs - Lights - Scene changed
max_exceeded: silent
trigger:
  - platform: state
    entity_id: input_select.hallway_downstairs_lights_scene
action:
  - service: scene.turn_on
    data:
      entity_id: scene.hallway_downstairs_lights_{{ trigger.to_state.state.replace(" ", "_") | lower }}
