---
id: attic_3d_printer_cancel_automatic_off
alias: Attic - 3D Printer cancel automatic off
trigger:
  - platform: state
    entity_id: sensor.attic_3d_printer_state
    to: 'printing'
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: automation.attic_3d_printer_automatic_off
        attribute: current
        above: 0
action:
  - service: automation.turn_off
    data:
      entity_id: automation.attic_3d_printer_automatic_off
  - service: automation.turn_on
    data:
      entity_id: automation.attic_3d_printer_automatic_off
