---
id: bedroom_eva_ceiling_light_on
alias: Bedroom Eva - Ceiling light on
max_exceeded: silent
trigger:
  - id: bedroom_eva_switch_top
    platform: device
    domain: hue
    device_id: 91af78cb691a3d71628398d93e9a1405
    type: initial_press
    subtype: 1
    unique_id: 4147c99a-80b4-4d0b-b5f8-006e9c2e845a
action:
  - choose:
      - conditions:
          - alias: "Early morning"
            condition: state
            entity_id: sensor.system_time_of_day_detailed
            state: "early_morning"
        sequence:
          - service: scene.turn_on
            data:
              entity_id: scene.bedroom_eva_lights_ceiling_on
              transition: 60

    # - conditions:
    #     - condition: state
    #       entity_id: light.bedroom_eva_ceiling
    #       state: 'on'
    #   sequence:
    #     - scene: scene.bedroom_eva_lights_ceiling_off

    # Default
    default:
      - service: scene.turn_on
        data:
          entity_id: scene.bedroom_eva_lights_ceiling_on
