---
id: attic_hallway_automatic_lights_timer_start
alias: Attic hallway - Automatic lights timer start
trigger:
  - platform: state
    entity_id: light.attic_hallway
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.attic_hallway_automatic_lights
    state: 'on'
action:
  - service: timer.start
    data:
      entity_id: timer.attic_hallway_automatic_lights
      duration: "{{ (states('input_number.attic_hallway_automatic_lights_duration') | float(0)) * 60 }}"
