---
id: attic_hallway_automatic_lights_off
alias: Attic hallway - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.attic_hallway_automatic_lights
condition:
  and:
    - condition: state
      entity_id: binary_sensor.attic_hallway_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.attic_hallway
      state: 'on'
action:
  - scene: scene.attic_hallway_lights_off
