---
id: attic_hallway_automatic_lights_off
alias: Attic hallway - Automatic lights off
trigger:
  - platform: state
    entity_id: light.attic_hallway
    to: 'on'
    for:
      minutes: 5
condition:
  and:
    - condition: state
      entity_id: binary_sensor.attic_hallway_automatic_lights
      state: 'on'
action:
  - scene: scene.attic_hallway_lights_off
