---
id: attic_hallway_ceiling_light_toggle
alias: Attic hallway - Ceiling light toggle
trigger:
  - platform: device
    domain: mqtt
    device_id: ccf0a1547052d19ede54940d64d9ee65
    type: action
    subtype: single_left
    discovery_id: 0x00158d0001f3f4fd action_single_left
  - platform: device
    domain: mqtt
    device_id: ccf0a1547052d19ede54940d64d9ee65
    type: action
    subtype: single_right
    discovery_id: 0x00158d0001f3f4fd action_single_right
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: light.attic_hallway
          state: 'off'
      sequence:
        - service: automation.trigger
          data:
            entity_id: automation.attic_hallway_ceiling_light_on
    - conditions:
        - condition: state
          entity_id: light.attic_hallway
          state: 'on'
      sequence:
        - service: automation.trigger
          data:
            entity_id: automation.attic_hallway_ceiling_light_off
