---
id: downstairs_garage_tablet_undim
alias: Downstairs Garage - Tablet undim
trigger:
  - platform: time
    at: "06:00:00"
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/garage/command
      payload: |
        {
          "brightness": 80
        }
