---
id: bedroom_nightstand_bernd_automatic_on
alias: Bedroom - Nightstand Bernd automatic on
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: 'on'

condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean.bedroom_bs_in_bed
      state:  'off'

action:
  - service: scene.turn_on
    data:
      entity_id: scene.bedroom_lights_nightstand_bernd_dimmed
      transition: 2
