---
id: bedroom_nightstands_off_when_ceiling_light_on_in_morning
alias: Bedroom - Nightstands off when ceiling light on in morning
trigger:
  - platform: state
    entity_id: light.bedroom_ceiling
    from: "off"
    to: "on"
condition:
  condition: or
  conditions:
    - condition: time
      after: "06:00:00"
      before: "09:00:00"
action:
  - service: scene.turn_on
    entity_id: scene.bedroom_lights_nightstands_off
