---
id: bedroom_nightstand_bernd_set_dimlevel
alias: Bedroom - Nightstand Bernd set dimlevel
trigger:
  - platform: state
    entity_id: sensor.bedroom_nightstand_bernd_remote
    to: brightness_up_click
  - platform: state
    entity_id: sensor.bedroom_nightstand_bernd_remote
    to: brightness_down_click
variables:
  percentage: |
    {% if trigger.to_state.state == 'brightness_up_click' -%}
      10
    {%- else -%}
      -10
    {%- endif %}
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_bernd
        state: 'off'
      sequence:
        - scene: scene.bedroom_lights_nightstand_bernd_dimmed
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_bernd
        state: 'on'
      sequence:
        - service: light.turn_on
          data:
            entity_id: light.bedroom_nightstand_bernd
            brightness_step_pct: "{{ percentage }}"

    # Default
    default: []
