---
id: bedroom_reset_persons_in_bed
alias: Bedroom - Reset persons in bed
trigger:
  - platform: time
    at: "06:10"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedroom_mf_in_bed
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.bedroom_bs_in_bed
