---
id: upstairs_hallway_automatic_lights_off
alias: Upstairs Hallway - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.upstairs_hallway_automatic_lights
condition:
  and:
    - condition: state
      entity_id: binary_sensor.upstairs_hallway_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.upstairs_hallway
      state: 'on'
action:
  - scene: scene.upstairs_hallway_lights_off
