---
id: upstairs_hallway_automatic_lights_timer_start
alias: Upstairs Hallway - Automatic lights timer start
trigger:
  - platform: state
    entity_id: light.upstairs_hallway
    to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.upstairs_hallway_automatic_lights
    state: "on"
action:
  - service: timer.start
    data:
      entity_id: timer.upstairs_hallway_automatic_lights
      duration: "{{ (states('input_number.upstairs_hallway_automatic_lights_duration') | float(0)) * 60 }}"
