---
id: upstairs_hallway_automatic_lights_off
alias: Upstairs Hallway - Automatic lights off
trigger:
  - platform: state
    entity_id: light.upstairs_hallway
    to: "on"
    for:
      minutes: 5
condition:
  and:
    - condition: state
      entity_id: binary_sensor.upstairs_hallway_automatic_lights
      state: 'on'
action:
  - scene: scene.upstairs_hallway_lights_off
