---
id: upstairs_hallway_ceiling_light_off
alias: Upstairs Hallway - Ceiling light off
max_exceeded: silent
trigger:
  - id: downstairs_hallway_stairs_switch_bottom_left
    platform: device
    domain: mqtt
    device_id: 66e77759181c96a80d427dd55b3e0d75
    type: action
    subtype: press_2
    discovery_id: 0x0000000001716b6f action_press_2

  - id: downstairs_hallway_stairs_switch_bottom_right
    platform: device
    domain: mqtt
    device_id: 66e77759181c96a80d427dd55b3e0d75
    type: action
    subtype: press_4
    discovery_id: 0x0000000001716b6f action_press_4

  - id: downstairs_hallway_stairs_switch_bottom
    platform: device
    domain: mqtt
    device_id: 66e77759181c96a80d427dd55b3e0d75
    type: action
    subtype: press_2_and_4
    discovery_id: 0x0000000001716b6f action_press_2_and_4

  - id: upstairs_hallway_switch_bottom_right
    platform: device
    domain: mqtt
    device_id: 4b41fc02c4f375ddbe1c405fe173600d
    type: action
    subtype: press_4
    discovery_id: 0x0000000001716b46 action_press_4

action:
  - scene: scene.upstairs_hallway_lights_off
