---
id: upstairs_hallway_ceiling_light_on
alias: Upstairs Hallway - Ceiling light on
max_exceeded: silent
trigger:
  - id: downstairs_hallway_stairs_switch_button_1_press
    platform: device
    domain: hue
    device_id: 0216651cf23a2289bc306de217391465
    type: initial_press
    subtype: 1
    unique_id: 2b8eb0e3-7aae-43cb-be0b-abaa540df5d9
  - id: upstairs_hallway_switch_button_3_press
    platform: device
    domain: hue
    device_id: fb2e69655f5862ce3a7c9f4dabc2e086
    type: initial_press
    subtype: 3
    unique_id: 16937cd2-50a9-46b9-bc6f-8285cfea929a

action:
  - scene: scene.upstairs_hallway_lights_on
