---
id: downstairs_hallway_tablet_turn_on
alias: Downstairs hallway - Tablet turn on
max_exceeded: silent
trigger:
  - id: hallway_presence
    platform: state
    entity_id:
      - binary_sensor.living_room_door_contact
      - binary_sensor.downstairs_hallway_front_door_contact
      - binary_sensor.downstairs_hallway_motion
    to: 'on'
  - id: returned_home
    platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: 'on'
    to: 'off'
action:
  - alias: "Wake up hallway tablet"
    service: switch.turn_on
    entity_id: switch.downstairs_hallway_tablet_screen
