---
id: downstairs_hallway_tablet_dim
alias: Downstairs hallway - Tablet dim
trigger:
  - platform: time
    at: "20:00:00"
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/hallway/command
      payload: |
        {
          "brightness": 50
        }
