---
id: downstairs_hallway_tablet_dim
alias: Downstairs hallway - Tablet dim
trigger:
  - platform: state
    entity_id: sensor.system_time_of_day
    from: "early_evening"
    to: "late_evening"
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/hallway/command
      payload: |
        {
          "brightness": 50
        }
