---
id: downstairs_hallway_tablet_turn_on
alias: Downstairs hallway - Tablet turn on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_front_door_contact
    to: 'on'
  - platform: state
    entity_id: binary_sensor.downstairs_hallway_motion
    to: 'on'
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: 'on'
    to: 'off'
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/hallway/command
      payload: |
        {
          "wake": true
        }
