---
id: upstairs_office_remote_on
alias: Upstairs office - Remote - On
trigger:
  - platform: device
    domain: mqtt
    device_id: f426e3a72e830a0f3444403d6e6694d9
    type: action
    subtype: on-press
    discovery_id: 0x0017880110493f0b action_on-press
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.upstairs_office_lights_scene
      option: 'Chill'
