---
id: upstairs_office_switch_off
alias: Upstairs office - Switch - Off
max_exceeded: silent
trigger:
  - id: upstairs_office_switch_bottom_left
    platform: device
    domain: mqtt
    device_id: d3d7eacc2f60052c0861c61f306afa52
    type: action
    subtype: press_2
    discovery_id: 0x0000000001716c1d action_press_2

  - id: upstairs_office_switch_bottom_right
    platform: device
    domain: mqtt
    device_id: d3d7eacc2f60052c0861c61f306afa52
    type: action
    subtype: press_4
    discovery_id: 0x0000000001716c1d action_press_4

  - id: upstairs_office_switch_bottom
    platform: device
    domain: mqtt
    device_id: d3d7eacc2f60052c0861c61f306afa52
    type: action
    subtype: press_2_and_4
    discovery_id: 0x0000000001716c1d action_press_2_and_4

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.upstairs_office_lights_scene
      option: "Off"
