---
id: hallway_tablet_dim
alias: Hallway - Tablet dim
trigger:
  - platform: time
    at: "20:00"
action:
  - service: light.turn_on
    data:
      entity_id: light.hallway_tablet
      brightness_pct: 50
