---
id: hallway_automatic_lights_timer_restart
alias: Hallway - Automatic lights timer (re)start
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_motion_2
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: timer.automatic_lights_hallway
      state: 'active'
    - condition: state
      entity_id: binary_sensor.hallway_automatic_lights
      state: 'on'
action:
  - service: timer.start
    data:
      entity_id: timer.automatic_lights_hallway
      duration: "{{ (states('input_number.automatic_lights_duration_hallway') | float) * 60 }}"
