---
id: hallway_automatic_lights_on
alias: Hallway - Automatic lights on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion_1
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_motion_2
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_front_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room_door
    to: 'on'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.hallway_automatic_lights
      state: 'on'
    - condition: state
      entity_id: binary_sensor.hallway_is_dark
      state: 'on'

action:
  - choose:
    - conditions:
        - condition: state
          entity_id: light.hallway
          state: 'off'
        - condition: time
          after: "20:00:00"
          before: "08:00:00"
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.hallway_lights_dimmed
            transition: 2

    - conditions:
        - condition: state
          entity_id: light.hallway
          state: 'off'
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.hallway_lights_on
            transition: 2

  - service: automation.trigger
    data:
      entity_id: automation.hallway_automatic_lights_timer_re_start
