---
id: hallway_ceiling_light_on
alias: Hallway - Ceiling light on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_1_and_3
    discovery_id: 0x000000000175799c action_press_1_and_3
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_1
    discovery_id: 0x000000000175799c action_press_1
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_3
    discovery_id: 0x000000000175799c action_press_3
action:
  - choose:
      - conditions:
          - condition: time
            after: "20:00:00"
            before: "08:00:00"
        sequence:
          - service: scene.turn_on
            data:
              entity_id: scene.hallway_lights_dimmed

    # Default
    default:
      - service: scene.turn_on
        data:
          entity_id: scene.hallway_lights_on

  - service: timer.cancel
    data:
      entity_id: timer.automatic_lights_hallway
