---
id: hallway_ceiling_light_off
alias: Hallway - Ceiling light off
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_2_and_4
    discovery_id: 0x000000000175799c action_press_2_and_4
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_2
    discovery_id: 0x000000000175799c action_press_2
  - platform: device
    domain: mqtt
    device_id: 5aea8955b04831c7ec33676a993335ed
    type: action
    subtype: press_4
    discovery_id: 0x000000000175799c action_press_4
action:
  - service: scene.turn_on
    data:
      entity_id: scene.hallway_lights_off

  - service: timer.cancel
    data:
      entity_id: timer.automatic_lights_hallway
