---
id: hallway_tablet_turn_on
alias: Hallway - Tablet turn on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.living_room_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_front_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.hallway_motion
    to: 'on'
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: 'on'
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.hallway_tablet_screensaver
