---
id: dining_area_lights_on
alias: Dining Area - Lights on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: cd02dc4dd7d89d84f13b6d1bc9a91efe
    type: action
    subtype: recall_scene_3
    discovery_id: 0x0000000001715668 action_recall_scene_3
action:
  - scene: scene.dining_area_lights_full_brightness
