---
id: turn_off_hass_recently_started
alias: turn off hass recently started
trigger:
  platform: homeassistant
  event: start
action:
  - delay: 00:00:30
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.maintenance_hass_recently_started
