---
id: home_bedtime_mode_on_turn_off_lights
alias: Home - Bedtime mode on turn off lights
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_bedtime_mode
    to: 'on'

action:
  - service: scene.turn_on
    data:
      entity_id: scene.backyard_lights_off

  - service: scene.turn_on
    data:
      entity_id: scene.kitchen_lights_off

  - service: scene.turn_on
    data:
      entity_id: scene.living_room_lights_off

  - service: scene.turn_on
    data:
      entity_id: scene.dining_area_lights_off

  - service: scene.turn_on
    data:
      entity_id: scene.study_lights_off

  - service: scene.turn_on
    data:
      entity_id: scene.hallway_study_lights_off

  - service: light.turn_off
    entity_id: light.bedroom_ceiling
