---
id: downstairs_toilet_lights_toggle
alias: Downstairs Toilet - Lights toggle
max_exceeded: silent
trigger:
  - id: downstairs_toilet_switch_top
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_1
    discovery_id: 00x001788010d30750a action_press_1

  - id: downstairs_toilet_switch_top
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_3
    discovery_id: 00x001788010d30750a action_press_3

  - id: downstairs_toilet_switch_top
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_1_and_3
    discovery_id: 00x001788010d30750a action_press_1_and_3

  - id: downstairs_toilet_switch_bottom
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_2
    discovery_id: 0x001788010d30750a action_press_2

  - id: downstairs_toilet_switch_bottom
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_4
    discovery_id: 0x001788010d30750a action_press_4

  - id: downstairs_toilet_switch_bottom
    platform: device
    domain: mqtt
    device_id: cf2988ca53251dfa0a847fc97e4763e3
    type: action
    subtype: press_2_and_4
    discovery_id: 0x001788010d30750a action_press_2_and_4

action:
  - service: light.toggle
    data:
      entity_id: light.downstairs_toilet_ceiling
