---
id: system_set_theme
alias: System - Set theme
max_exceeded: silent
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reload
  - platform: state
    entity_id: binary_sensor.driveway_is_dark
action:
  - service: frontend.set_theme
    data:
      name: |
        {%- if is_state("binary_sensor.driveway_is_dark", "on") -%}
          minimalist-dark
        {%- else -%}
          minimalist-light
        {%- endif -%}
