---
id: study_upstairs_switch_on
alias: Study Upstairs - Switch - On
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: d3d7eacc2f60052c0861c61f306afa52
    type: action
    subtype: recall_scene_3
    discovery_id: 0x0000000001716c1d action_recall_scene_3
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.study_upstairs_active_lights_scene
      option: |
        {% set entity_id = "input_select.study_upstairs_active_lights_scene" %}
        {% set options = state_attr(entity_id, "options") %}
        {% set selection = options.index(states(entity_id)) %}
        {% if (selection + 1) >= options | length %}
          {{ options[1] }}
        {% else %}
          {{ options[selection + 1] }}
        {% endif %}
