---
id: study_upstairs_switch_off
alias: Study Upstairs - Switch - Off
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: d3d7eacc2f60052c0861c61f306afa52
    type: action
    subtype: recall_scene_2
    discovery_id: 0x0000000001716c1d action_recall_scene_2
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.study_upstairs_active_lights_scene
      option: 'Off'
