---
id: utility_room_toggle_vacuum
alias: Utility room - Toggle automatic vacuum
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.utility_room_door_contact
action:
  - service: input_boolean.turn_'{{ "off" if trigger.to_state.state == "on" else "on" }}'
    entity_id: input_boolean.utility_room_vacuum
