---
id: bedroom_nightstand_manyie_set_dimlevel
alias: Bedroom - Nightstand ManYie set dimlevel
trigger:
  - platform: state
    entity_id: sensor.bedroom_nightstand_manyie_remote
    to: brightness_up_click
  - platform: state
    entity_id: sensor.bedroom_nightstand_manyie_remote
    to: brightness_down_click
variables:
  target: light.bedroom_nightstand_manyie
  min_brightness: 0
  max_brightness: 254
  percentage: |
    {% if trigger.to_state.state == 'brightness_up_click' -%}
      5
    {%- else -%}
      -5
    {%- endif %}
action:
  - choose:
    - conditions:
      - condition: template
        value_template: |
          {{ is_state(target, 'off') }}
      sequence:
        - scene: scene.bedroom_lights_nightstand_manyie_dimmed
    - conditions:
      - condition: template
        value_template: |
          {{ is_state(target, 'on') }}
      - condition: template
        value_template: |
          {{ ((state_attr(target, 'brightness')/max_brightness * 100) | int ) + (percentage | int) > min_brightness }}
      - condition: template
        value_template: |
          {{ ((state_attr(target, 'brightness')/max_brightness * 100) | int ) + (percentage | int) <= max_brightness }}
      sequence:
        - service: light.turn_on
          data:
            entity_id: "{{ target }}"
            brightness_step_pct: "{{ percentage }}"

    # Default
    default: []
  