---
id: bedroom_nightstand_manyie_toggle
alias: Bedroom - Nightstand ManYie toggle
trigger:
  - platform: state
    entity_id: sensor.bedroom_nightstand_manyie_remote
    to: toggle
  - platform: state
    entity_id: sensor.bedroom_nightstand_bernd_remote
    to: arrow_left_click
action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_manyie
        state: 'off'
      sequence:
        - scene: scene.bedroom_lights_nightstand_manyie_dimmed
    - conditions:
      - condition: state
        entity_id: light.bedroom_nightstand_manyie
        state: 'on'
      sequence:
        - scene: scene.bedroom_lights_nightstand_manyie_off

    # Default
    default: []
