---
id: garage_tablet_dim
alias: Garage - Tablet dim
trigger:
  - platform: time
    at: "20:00:00"
action:
  - service: light.turn_on
    data:
      entity_id: light.garage_tablet_screen
      brightness_pct: 50
