---
id: garage_tablet_turn_on
alias: Garage - Tablet turn on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.garage_entry_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.garage_motion
    to: 'on'
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: 'on'
    to: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.garage_tablet_screensaver
