---
id: kitchen_automatic_lights_on
alias: Kitchen - Automatic lights on
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.automatic_lights_kitchen
      state: 'on'
    - condition: state
      entity_id: binary_sensor.is_dark_kitchen
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'off'
action:
  - choose:
    - conditions:
        - condition: time
          after: "20:00:00:00"
          before: "02:00:00"
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.kitchen_lights_relaxed
            transition: 2
    
    default:
      - service: scene.turn_on
        data:
          entity_id: scene.kitchen_lights_full_brightness
          transition: 2

  - service: automation.trigger
    data:
      entity_id: automation.kitchen_automatic_lights_timer_re_start
