---
id: kitchen_automatic_lights_off
alias: Kitchen - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.automatic_lights_kitchen
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.automatic_lights_kitchen
      state: 'on'
    - condition: state
      entity_id: light.kitchen
      state: 'on'
action:
  - choose:
    # No more motion, turn off the lights
    - conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_motion
          state: 'off'
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.kitchen_lights_off
            transition: 2
    
    # Motion still detected, restart the timer
    - conditions:
        - condition: state
          entity_id: binary_sensor.kitchen_motion
          state: 'on'
      sequence:
        - service: automation.trigger
          data:
            entity_id: automation.kitchen_automatic_lights_timer_re_start
      