---
id: kitchen_automatic_lights_timer_restart
alias: Kitchen - Automatic lights timer (re)start
max_exceeded: silent
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: timer.automatic_lights_kitchen
      state: 'active'
    - condition: state
      entity_id: binary_sensor.kitchen_automatic_lights
      state: 'on'
action:
  - service: timer.start
    data:
      entity_id: timer.automatic_lights_kitchen
      duration: "{{ (states('input_number.automatic_lights_duration_kitchen') | float) * 60 }}"
  