---
id: kitchen_lights_on
alias: Kitchen - Lights on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: cd02dc4dd7d89d84f13b6d1bc9a91efe
    type: action
    subtype: press_1
    discovery_id: 0x0000000001715668 action_press_1
action:
  - scene: scene.kitchen_lights_full_brightness
