---
id: kitchen_lights_off
alias: Kitchen - Lights off
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: cd02dc4dd7d89d84f13b6d1bc9a91efe
    type: action
    subtype: press_2
    discovery_id: 0x0000000001715668 action_press_2
action:
  - scene: scene.kitchen_lights_off
