---
id: home_alarm_arm_away_automatically
alias: Home - Alarm - Arm Away automatically
trigger:
  - platform: state
    entity_id: input_boolean.home_modes_away_mode
    to: 'on'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'disarmed'

action:
  # Wait until vacuum is docked
  - choose:
      - alias: "Wait until vacuum is docked"
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: vacuum.valetudo_livingroom
                state: 'docked'
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: vacuum.valetudo_livingroom
                to: 'docked'
  
  # Arm alarm
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.house
