---
id: home_alarm_arming
alias: Home - Alarm arming
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarmo
    to: 'arming'

action:
  # Warning beep
  - service: fullykiosk.play_audio
    data:
      entity_id: 
        - media_player.hallway_tablet_media_player
        - media_player.garage_tablet_media_player
      url: "{{ states('sensor.system_url_internal') }}/local/audio/beep-warning.mp3"
      stream: 3
