---
id: home_alarm_pending
alias: Home - Alarm pending
trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'

action:
  # Alert beep
  - event: wallpanels_publish_payload
    event_data:
      payload: |
        {
          "audio": "{{ states('sensor.system_url_internal_direct') }}/local/audio/beep-alarm.mp3"
        }
