---
id: attic_3d_printer_notification_done
alias: Attic - 3D Printer notification - Done
trigger:
  - platform: state
    entity_id: binary_sensor.attic_ender_3_printing
    from: 'on'
    to: 'off'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.attic_3d_printer_notifications
        state: 'on'
action:
  - service: notify.slack_bot
    data:
      message: "3D Printer is done"
      target: "@bernd"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "3D Printer is done"
