---
id: attic_3d_printer_automatic_off
alias: Attic - 3D Printer automatic off
trigger:
  - platform: state
    entity_id: binary_sensor.attic_ender_3_printing
    from: 'on'
    to: 'off'
action:
  - wait_template: |
      {{ 
        states('sensor.attic_ender_3_bed_temperature') | float < 30
        and
        states('sensor.attic_ender_3_tool_0_temperature') | float < 50
      }}
    continue_on_timeout: 'true'
    timeout: 00:30:00
  - service: switch.turn_off
    data:
      entity_id: switch.study_3d_printer
