---
id: attic_lights_scene_changed
alias: Attic - Lights scene changed
max_exceeded: silent
trigger:
  - platform: state
    entity_id: input_select.attic_lights_scene
action:
  - service: scene.turn_on
    data:
      entity_id: scene.attic_lights_{{ trigger.to_state.state.replace(" ", "_") | lower }}
