---
id: attic_rear_ceiling_light_toggle
alias: Attic - Rear ceiling light toggle
trigger:
  - platform: device
    domain: mqtt
    device_id: 50905b5ed0f10f4c253b254088525b7f
    type: action
    subtype: single_left
    discovery_id: 0x00158d0002fcea27 action_single_left
  - platform: device
    domain: mqtt
    device_id: df0f3d49be139fa0b32df312af3d9bf8
    type: action
    subtype: on-press
    discovery_id: 0x0017880110493d0c action_on-press
  - platform: device
    domain: mqtt
    device_id: df0f3d49be139fa0b32df312af3d9bf8
    type: action
    subtype: off-press
    discovery_id: 0x0017880110493d0c action_off-press
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: light.attic_rear_ceiling
          state: 'off'
      sequence:
        - scene: scene.attic_lights_rear_full_brightness
    - conditions:
        - condition: state
          entity_id: light.attic_rear_ceiling
          state: 'on'
      sequence:
        - scene: scene.attic_lights_rear_off
