---
id: hallway_study_automatic_lights_off
alias: Hallway Study - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.automatic_lights_hallway_study
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.hallway_study_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.hallway_study
      state: 'on'
action:
  - scene: scene.hallway_study_lights_off
