---
id: hallway_study_automatic_lights_timer_start
alias: Hallway Study - Automatic lights timer start
trigger:
  - platform: state
    entity_id: light.hallway_study
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.hallway_study_automatic_lights
      state: 'on'
action:
  - service: timer.start
    data:
      entity_id: timer.automatic_lights_hallway_study
      duration: "{{ (states('input_number.automatic_lights_duration_hallway_study') | float) * 60 }}"
