---
id: backyard_lights_off
alias: Backyard - Lights off
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: dd81282b220b5523490be40a8cb92b6e
    type: action
    subtype: recall_scene_2
    discovery_id: 0x000000000171680f action_recall_scene_2
action:
  - scene: scene.backyard_lights_off
