---
id: backyard_lights_on
alias: Backyard - Lights on
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: dd81282b220b5523490be40a8cb92b6e
    type: action
    subtype: recall_scene_3
    discovery_id: 0x000000000171680f action_recall_scene_3
action:
  - scene: scene.backyard_lights_on
