---
id: attic_office_lights_scene_controller
alias: Attic office - Lights - Scene controller
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: 50905b5ed0f10f4c253b254088525b7f
    type: action
    subtype: single_left
    discovery_id: 0x00158d0002fcea27 action_single_left
    id: switch-left-click
  - platform: device
    domain: mqtt
    device_id: 50905b5ed0f10f4c253b254088525b7f
    type: action
    subtype: hold_left
    discovery_id: 0x00158d0002fcea27 action_hold_left
    id: switch-left-hold

action:
  - alias: "choose scene based on trigger"
    choose:
      # Loop through scenes
      - conditions:
          - condition: trigger
            id: switch-left-click
        sequence:
          - service: input_select.select_next
            data:
              entity_id: input_select.attic_office_lights_scene

      # Select "off" scene
      - conditions:
          - condition: trigger
            id: switch-left-hold
        sequence:
          - service: input_select.select_option
            data:
              entity_id: input_select.attic_office_lights_scene
              option: 'Off'
