---
id: attic_office_lights_scene_controller
alias: Attic office - Lights - Scene controller
max_exceeded: silent

trigger:
  - id: attic_office_switch_top_left
    platform: device
    domain: hue
    device_id: 5fe0720b32b486172c92638045ca1617
    type: initial_press
    subtype: 1
    unique_id: 22296b02-232c-48e3-8513-861d88a9e785
  - id: attic_office_switch_bottom_left
    platform: device
    domain: hue
    device_id: 5fe0720b32b486172c92638045ca1617
    type: initial_press
    subtype: 2
    unique_id: c1461518-4e7d-43d1-84b1-8c553d7e5f65
  - id: attic_office_switch_top_right
    platform: device
    domain: hue
    device_id: 5fe0720b32b486172c92638045ca1617
    type: initial_press
    subtype: 3
    unique_id: 8baca6a0-e173-4609-89df-dea50e956fef
  - id: attic_office_switch_bottom_right
    platform: device
    domain: hue
    device_id: 5fe0720b32b486172c92638045ca1617
    type: initial_press
    subtype: 4
    unique_id: 29af5843-83df-4d03-ad99-cf0e4e3e3bb6

  - platform: device
    domain: hue
    device_id: 9917ddec2ef16af8b855f70b76332092
    type: initial_press
    subtype: 1
    unique_id: df6ae429-d35b-453e-a11d-7c34109a4000
    id: remote-on-click
  - platform: device
    domain: hue
    device_id: 9917ddec2ef16af8b855f70b76332092
    type: initial_press
    subtype: 4
    unique_id: 07167d34-d914-4efd-b7c3-3d8a3cc0481c
    id: remote-off-click

  - id: lights_turned_off
    platform: state
    entity_id: light.attic
    from: "on"
    to: "off"

action:
  - alias: "choose scene based on trigger"
    choose:
      # Select "Work" scene
      - conditions:
          - and:
              - or:
                  - condition: trigger
                    id: attic_office_switch_top_left
                  - condition: trigger
                    id: remote-on-click
              - condition: state
                entity_id: light.attic_office_rear_ceiling
                state: "off"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: input_select.attic_office_lights_scene
              option: "Work"

      # Loop through "On" scenes
      - conditions:
          - and:
              - or:
                  - condition: trigger
                    id: attic_office_switch_top_left
                  - condition: trigger
                    id: remote-on-click
              - condition: state
                entity_id: light.attic_office_rear_ceiling
                state: "on"
        sequence:
          - service: script.input_select_next_with_skip
            data:
              entity_id: input_select.attic_office_lights_scene
              skip_options:
                - "Off"

      # Select "off" scene
      - conditions:
          - or:
              - condition: trigger
                id: attic_office_switch_bottom_left
              - alias: "Remote Off button"
                condition: trigger
                id: remote-off-click
              - alias: "Lights turned off otherwise"
                condition: trigger
                id: lights_turned_off
        sequence:
          - service: input_select.select_option
            data:
              entity_id: input_select.attic_office_lights_scene
              option: "Off"

      # Turn on front lights
      - conditions:
          - condition: trigger
            id: attic_office_switch_top_right
        sequence:
          - scene: scene.attic_office_lights_front_full_brightness

      # Turn off front lights
      - conditions:
          - condition: trigger
            id: attic_office_switch_bottom_right
        sequence:
          - scene: scene.attic_office_lights_front_off
