---
id: attic_office_lights_scene_controller
alias: Attic office - Lights - Scene controller
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: 50905b5ed0f10f4c253b254088525b7f
    type: action
    subtype: single_left
    discovery_id: 0x00158d0002fcea27 action_single_left
    id: switch-left-click
  - platform: device
    domain: mqtt
    device_id: 50905b5ed0f10f4c253b254088525b7f
    type: action
    subtype: hold_left
    discovery_id: 0x00158d0002fcea27 action_hold_left
    id: switch-left-hold
  - platform: device
    domain: mqtt
    device_id: df0f3d49be139fa0b32df312af3d9bf8
    type: action
    subtype: on-press
    discovery_id: 0x0017880110493d0c action_on-press
    id: remote-on-click
  - platform: device
    domain: mqtt
    device_id: df0f3d49be139fa0b32df312af3d9bf8
    type: action
    subtype: off-press
    discovery_id: 0x0017880110493d0c action_off-press
    id: remote-off-click
  - id: lights_turned_off
    platform: state
    entity_id: light.attic
    from: "on"
    to: "off"

action:
  - alias: "choose scene based on trigger"
    choose:
      # Loop through scenes
      - conditions:
          - condition: trigger
            id: remote-on-click
        sequence:
          - service: script.input_select_next_with_skip
            data:
              entity_id: input_select.attic_office_lights_scene
              skip_options:
                - "Off"

      # Select "on" scene
      - conditions:
          - and:
              - condition: trigger
                id: switch-left-click
              - condition: state
                entity_id: light.attic_office_rear_ceiling
                state: "off"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: input_select.attic_office_lights_scene
              option: "Work"

      # Select "off" scene
      - conditions:
          - or:
              - and:
                  - condition: trigger
                    id: switch-left-click
                  - condition: state
                    entity_id: light.attic_office_rear_ceiling
                    state: "on"
              - alias: "Remote Off button"
                condition: trigger
                id: remote-off-click
              - alias: "Lights turned off otherwise"
                condition: trigger
                id: lights_turned_off
        sequence:
          - service: input_select.select_option
            data:
              entity_id: input_select.attic_office_lights_scene
              option: "Off"
