---
id: downstairs_garage_tablet_dim
alias: Downstairs Garage - Tablet dim
trigger:
  - platform: time
    at: "20:00:00"
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/garage/command
      payload: |
        {
          "brightness": 50
        }
