---
id: downstairs_garage_tablet_undim
alias: Downstairs Garage - Tablet undim
trigger:
  - platform: state
    entity_id: sensor.system_time_of_day
    from: "night"
    to: "early_morning"
action:
  - service: mqtt.publish
    data_template:
      topic: wallpanel/garage/command
      payload: |
        {
          "brightness": 80
        }
