---
id: downstairs_garage_tablet_turn_on
alias: Downstairs Garage - Tablet turn on
max_exceeded: silent
trigger:
  - id: garage_presence
    platform: state
    entity_id: binary_sensor.downstairs_garage_door_contact
    to: 'on'
  - id: garage_presence
    platform: state
    entity_id: binary_sensor.downstairs_garage_entry_door_contact
    to: 'on'
  - id: garage_presence
    platform: state
    entity_id: binary_sensor.downstairs_garage_motion
    to: 'on'
  - id: returned_home
    platform: state
    entity_id: input_boolean.home_modes_away_mode
    from: 'on'
    to: 'off'

action:
  - alias: "Wake up garage tablet"
    service: switch.turn_off
    entity_id: switch.downstairs_garage_tablet_screensaver
