---
id: bedroom_eva_ceiling_light_toggle
alias: Bedroom Eva - Ceiling light toggle
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: 69f575f7db8e116d27f324a335bdb26b
    type: click
    subtype: single
    discovery_id: 0x00158d0001833e04 click_single
action:
  - choose:
    - conditions:
        - condition: state
          entity_id: light.bedroom_eva_ceiling
          state: 'off'
        - condition: time
          after: "06:00:00"
          before: "08:30:00"
      sequence:
        - service: scene.turn_on
          data:
            entity_id: scene.bedroom_eva_lights_ceiling_on
            transition: 120
    - conditions:
        - condition: state
          entity_id: light.bedroom_eva_ceiling
          state: 'off'
      sequence:
        - scene: scene.bedroom_eva_lights_ceiling_on
    - conditions:
        - condition: state
          entity_id: light.bedroom_eva_ceiling
          state: 'on'
      sequence:
        - scene: scene.bedroom_eva_lights_ceiling_off

    # Default
    default: []
