---
id: hallway_upstairs_automatic_lights_off
alias: Hallway Upstairs - Automatic lights off
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.automatic_lights_hallway_upstairs
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.hallway_upstairs_automatic_lights
      state: 'on'
    - condition: state
      entity_id: light.hallway_upstairs
      state: 'on'
action:
  - scene: scene.hallway_upstairs_lights_off
