---
id: living_room_lights_scene_changed
alias: Living Room - Lights scene changed
max_exceeded: silent
trigger:
  - platform: state
    entity_id: input_select.living_room_lights_scene
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_lights_{{ trigger.to_state.state.replace(" ", "_") | lower }}
      transition: 1
