---
binary_sensor:
  - name: Dining area - Is dark
    unique_id: dining_area_is_dark
    state: >
      {% set is_dark_lux = (states('input_number.dining_area_is_dark_lux') | float(0)) %}
      {%- if states('light.dining_area_ceiling') == "on" -%}
        {% set is_dark_lux = is_dark_lux + 10 %}
      {%- endif -%}
      {{
        (states('sensor.dining_area_motion_sensor_illuminance_lux') | float(0)) < is_dark_lux
      }}
    icon: >
      {% if (this.state | default("off")) == "on" %}
        mdi:brightness-4
      {%- else -%}
        mdi:brightness-5
      {%- endif -%}
