---
id: hallway_study_automatic_lights_timer_cancel
alias: Hallway Study - Automatic lights timer cancel
trigger:
  - platform: state
    entity_id: light.hallway_study
    to: 'off'
  - platform: state
    entity_id: binary_sensor.automatic_lights_hallway_study
    to: 'off'
action:
  - service: timer.cancel
    data:
      entity_id: timer.automatic_lights_hallway_study
