---
id: hallway_study_ceiling_light_on
alias: Hallway Study - Ceiling light on
max_exceeded: silent
trigger:
  - platform: state
    entity_id: sensor.hallway_upstairs_switch
    to: recall_scene_0
action:
  - scene: scene.hallway_study_lights_on
