---
id: study_3d_printer_notification_almost_done
alias: Study - 3D Printer notification - Almost done
trigger:
  - platform: numeric_state
    entity_id: sensor.study_octoprint_print_progress
    above: 90
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.study_3d_printer_notifications
        state: 'on'
      - condition: template
        value_template: |
          {{ (as_timestamp(now()) - as_timestamp(state_attr('automation.study_3d_printer_notification_almost_done', 'last_triggered') | default(0)) | int > 3600)}}    
action:
  - service: notify.slack_bot
    data:
      message: "3D Printer is at {{ states('sensor.study_octoprint_print_progress') }}%"
      target: "@bernd"
      data:
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: "3D Printer is at {{ states('sensor.study_octoprint_print_progress') }}%. Estimated print time left: {{ states('sensor.study_octoprint_print_time_left') }}"
