---
id: study_3d_printer_cancel_automatic_off
alias: Study - 3D Printer cancel automatic off
trigger:
  - platform: state
    entity_id: binary_sensor.study_octoprint_printing
    from: 'off'
    to: 'on'
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: automation.study_3d_printer_automatic_off
        attribute: current
        above: 0
action:
  - service: automation.turn_off
    data:
      entity_id: automation.study_3d_printer_automatic_off
  - service: automation.turn_on
    data:
      entity_id: automation.study_3d_printer_automatic_off
