---
id: study_3d_printer_automatic_off
alias: Study - 3D Printer automatic off
trigger:
  - platform: state
    entity_id: binary_sensor.study_octoprint_printing
    from: 'on'
    to: 'off'
action:
  - wait_template: |
      {{ 
        states('sensor.study_octoprint_temperature_bed_actual') | float < 30
        and
        states('sensor.study_octoprint_temperature_hotend_actual') | float < 50
      }}
    continue_on_timeout: 'true'
    timeout: 00:30:00
  - service: switch.turn_off
    data:
      entity_id: switch.study_3d_printer
