---
id: study_automatic_lights_timer_cancel
alias: Study - Automatic lights timer cancel
trigger:
  - platform: state
    entity_id: light.study
    to: 'off'
  - platform: state
    entity_id: binary_sensor.attic_automatic_lights
    to: 'off'
action:
  - service: timer.cancel
    data:
      entity_id: timer.automatic_lights_study
